spring.application.name: cloud-service-center

#服务注册中心端口号
server.port: 7000

spring.security.user:
    name: young
    password: 123456

eureka.instance:
    #服务注册中心实例的主机名
    hostname: localhost
    #服务续约
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30

eureka.client:
    #是否向服务注册中心注册自己
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url.defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/


