server:
  port: 7002

eureka.instance:
    #服务注册中心实例的主机名
    hostname: local2

eureka.client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url.defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:7001/eureka/
